BetonMashNew/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BetonMashNew.Models;

namespace BetonMashNew.Controllers
{
    public class SystemController : Controller
    {
        //
        // GET: /System/
        public ActionResult GetRegionsSelect(int id = 0)
        {
            using (ApplicationDbContext mb = new ApplicationDbContext())
            {
                return PartialView("Partial1", mb.Regions.Where(x => x.Country == id).ToList());
            }
        }

        public ActionResult GetCitiesSelect(int id = 0)
        {
            using (ApplicationDbContext mb = new ApplicationDbContext())
            {
                return PartialView("Partial2", mb.Cities.Where(x => x.Region == id).ToList());
            }
        }

        public ActionResult Error(string Error)
        {
            ViewBag.Er = Error;
            return View("Partial3");

        }
	}
}

BetonMashNew/Views/Admin/Clients.cshtml
@using BetonMashNew.Models
@{
    ViewBag.Title = "Клиенты";
}


@if (ViewBag.Clients != null)
{
    <h2>Клиенты @ViewBag.Name</h2>
<table id="myTable" class="tablesorter">
    <thead>
        <tr>
                <th>Клиент (код ОКПО)</th>
                <th>Регион</th>
                <th>Населенный пукнт</th>
                <th>Примечание</th>
            </tr>
        </thead>


        @foreach (ClientCi a in ViewBag.Clients)
        {
        <tr>
            <td>
                @a.NameCompany
            </td>
            <td>
                @a.NameRegion
            </td>
            <td>
               @a.NameCity
            </td>
            <td>
                @if (a.Note != null)
                {
                    if (a.Note.Length > 40)
                    {
                        string NoteV = a.Note.Replace("\r\n", "");
                        @a.Note.Substring(0, 36) <a href="#" onclick="ale('@NoteV');return false">отбр</a>
                    }
                    else
                    {
                        @a.Note
                    }
                }
            </td>
        </tr>
        }
    </table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery.tablesorter.min.js")

    <script type="text/javascript">

        $(document).ready(function () {
            $("#myTable").tablesorter();
        });

        function ale(a)
        {
            alert(a);
        }
    </script>
}

BetonMashNew/Views/Admin/Dealer.cshtml
@if (ViewBag.Del != null)
{
    <table id="myTable" class="tablesorter">
        <thead>
            <tr>
                <th>Наименование</th>
                <th>E-mail</th>
                @if(ViewBag.M == false)
                { 
                <th>Код ОКПО</th>
                <th>Страна</th>
                <th>Регион</th>
                <th>Населенный пукнт</th>
                }
                <th>Регионы влияния</th>
            </tr>
        </thead>
        <tbody>
            @foreach (BetonMashNew.Models.AdminInfo a in ViewBag.Del)
            {
                <tr>
                    <td>
                        @Html.ActionLink(a.NameCompany, "Clients", new { id = a.UserName })                       
                    </td>
                    <td>
                        @a.Email
                    </td>
                    @if(ViewBag.M == false)
                    { 
                    <td>
                        @a.KodOPK
                    </td>

                    <td>
                        @a.ContryName
                    </td>
                    <td>
                        @a.RegionName
                    </td>
                    <td>
                        @a.CityName
                    </td>
                    }
                    <td>
                        @a.Reg
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery.tablesorter.min.js")

    <script type="text/javascript">
    

        $(document).ready(function () {
            $("#myTable").tablesorter();
        });


    </script>
}

BetonMashNew/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Клиенты";
}

<h2>Информация</h2>

<div>
            @using (Ajax.BeginForm("Info", "Admin", new AjaxOptions { UpdateTargetId = "results" }, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="form-group">

                <div class="col-md-10">
                    <select id="Country" name="Country" class="form-control">
                        @foreach (BetonMashNew.Models.CountryCl a in ViewBag.Countries)
                        {
                            <option value="@a.CountryId">@a.Name</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">

                <div class="col-md-10">
                    <select id="Region" name="Region" class="form-control">
                            <option value="0">- Все регионы -</option>
                    </select>
                </div>
            </div>

            <div class="form-group">

                <div class="col-md-10">
                    <select id="City" name="City" class="form-control">  
                            <option value="0">- Все города -</option>
                    </select>
                </div>
            </div>
            <input type="submit" value="Применить фильтр" class="btn btn-default" />
        }
        <p>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Дилер/Менеджер (код ОКПО)</th>
                        <th>Клиент (код ОКПО)</th>
                        <th>Регион</th>
                        <th>Населенный пукнт</th>
                        <th>Примечание</th>
                    </tr>
                </thead>
                <tbody id="results"></tbody>
            </table>
        </p>
    </div>
<p>@Html.ActionLink("Все дилеры", "Dealer", new { id=0 })</p>
<p>@Html.ActionLink("Все менеджеры", "Dealer", new { id = 1 })</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")


<script type="text/javascript">

    $(function () {

        $('#Country').change(function () {
            $('#Region').html('<option value="0">- Все регионы -</option>');
            $('#City').html('<option value="0">- Все регионы -</option>');
            // получаем выбранный id
            var id = $(this).val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetRegionsSelect", "System")/' + id,
                success: function (data) {

                    // заменяем содержимое присланным частичным представлением
                    $('#Region').html('<option value="0">- Все регионы -</option>' + data);
                }
            });
        });
        $('#Region').change(function () {
            // получаем выбранный id
            $('#City').html('<option value="0">- Выберите город -</option>');
            var id = $('#Region').val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetCitiesSelect", "System")/' + id,
                success: function (data) {

                    // заменяем содержимое присланным частичным представлением
                    $('#City').html('<option value="0">- Все города -</option>' + data);
                }
            });
        });
    })

    function ale(a) {
        alert(a);
    }
    </script>    
    }

BetonMashNew/Views/Admin/Partial1.cshtml
@using BetonMashNew.Models
@if(ViewBag.Clients!= null)
{ 
    foreach(ClientCi a in ViewBag.Clients)
    { 
<tr>
    <td>
        @a.Dealer
    </td>
    <td>
        @a.NameCompany
    </td>
    <td>
        @Ajax.ActionLink(@a.NameRegion, "Info", new { Country = a.Country, Region = a.Region  }, new AjaxOptions { UpdateTargetId = "results", HttpMethod = "Get" })
    </td>
    <td>        
        @Ajax.ActionLink(@a.NameCity, "Info", new { Country = a.Country, Region = a.Region, City=a.City }, new AjaxOptions { UpdateTargetId = "results", HttpMethod = "Get" })
    </td>
    <td>
        @if (a.Note != null)
        {
            if (a.Note.Length > 40)
            {
                string NoteV = a.Note.Replace("\r\n", "");
                @a.Note.Substring(0, 36) <a href="#" onclick="ale('@NoteV');return false">отбр</a>
            }
            else
            {
                @a.Note
            }
        }
    </td>
</tr>
}
}